//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.07 at 02:43:07 PM GMT-10:00 
//


package org.hackystat.tickertape.configuration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SensorbaseHost"/>
 *         &lt;element ref="{}DailyProjectDataHost"/>
 *         &lt;element ref="{}User"/>
 *         &lt;element ref="{}Password"/>
 *         &lt;element ref="{}ProjectName"/>
 *         &lt;element ref="{}ProjectOwner"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sensorbaseHost",
    "dailyProjectDataHost",
    "user",
    "password",
    "projectName",
    "projectOwner"
})
@XmlRootElement(name = "Hackystat")
public class Hackystat {

    @XmlElement(name = "SensorbaseHost", required = true)
    protected String sensorbaseHost;
    @XmlElement(name = "DailyProjectDataHost", required = true)
    protected String dailyProjectDataHost;
    @XmlElement(name = "User", required = true)
    protected String user;
    @XmlElement(name = "Password", required = true)
    protected String password;
    @XmlElement(name = "ProjectName", required = true)
    protected String projectName;
    @XmlElement(name = "ProjectOwner", required = true)
    protected String projectOwner;

    /**
     * Gets the value of the sensorbaseHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorbaseHost() {
        return sensorbaseHost;
    }

    /**
     * Sets the value of the sensorbaseHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorbaseHost(String value) {
        this.sensorbaseHost = value;
    }

    /**
     * Gets the value of the dailyProjectDataHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDailyProjectDataHost() {
        return dailyProjectDataHost;
    }

    /**
     * Sets the value of the dailyProjectDataHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDailyProjectDataHost(String value) {
        this.dailyProjectDataHost = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the projectOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectOwner() {
        return projectOwner;
    }

    /**
     * Sets the value of the projectOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectOwner(String value) {
        this.projectOwner = value;
    }

}
