//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.07 at 02:43:07 PM GMT-10:00 
//


package org.hackystat.tickertape.configuration.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hackystat.tickertape.configuration.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SerialNumber_QNAME = new QName("", "SerialNumber");
    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _ProjectName_QNAME = new QName("", "ProjectName");
    private final static QName _Password_QNAME = new QName("", "Password");
    private final static QName _SensorbaseHost_QNAME = new QName("", "SensorbaseHost");
    private final static QName _ProjectOwner_QNAME = new QName("", "ProjectOwner");
    private final static QName _DailyProjectDataHost_QNAME = new QName("", "DailyProjectDataHost");
    private final static QName _Token_QNAME = new QName("", "Token");
    private final static QName _WakeupInterval_QNAME = new QName("", "WakeupInterval");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hackystat.tickertape.configuration.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Twitter }
     * 
     */
    public Twitter createTwitter() {
        return new Twitter();
    }

    /**
     * Create an instance of {@link Hackystat }
     * 
     */
    public Hackystat createHackystat() {
        return new Hackystat();
    }

    /**
     * Create an instance of {@link Tickertape }
     * 
     */
    public Tickertape createTickertape() {
        return new Tickertape();
    }

    /**
     * Create an instance of {@link Nabaztag }
     * 
     */
    public Nabaztag createNabaztag() {
        return new Nabaztag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SerialNumber")
    public JAXBElement<String> createSerialNumber(String value) {
        return new JAXBElement<String>(_SerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User")
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectName")
    public JAXBElement<String> createProjectName(String value) {
        return new JAXBElement<String>(_ProjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SensorbaseHost")
    public JAXBElement<String> createSensorbaseHost(String value) {
        return new JAXBElement<String>(_SensorbaseHost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectOwner")
    public JAXBElement<String> createProjectOwner(String value) {
        return new JAXBElement<String>(_ProjectOwner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DailyProjectDataHost")
    public JAXBElement<String> createDailyProjectDataHost(String value) {
        return new JAXBElement<String>(_DailyProjectDataHost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Token")
    public JAXBElement<String> createToken(String value) {
        return new JAXBElement<String>(_Token_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WakeupInterval")
    public JAXBElement<Integer> createWakeupInterval(Integer value) {
        return new JAXBElement<Integer>(_WakeupInterval_QNAME, Integer.class, null, value);
    }

}
