//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.07 at 02:43:07 PM GMT-10:00 
//


package org.hackystat.tickertape.configuration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Hackystat"/>
 *         &lt;element ref="{}Nabaztag" minOccurs="0"/>
 *         &lt;element ref="{}Twitter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hackystat",
    "nabaztag",
    "twitter"
})
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "Hackystat", required = true)
    protected Hackystat hackystat;
    @XmlElement(name = "Nabaztag")
    protected Nabaztag nabaztag;
    @XmlElement(name = "Twitter")
    protected Twitter twitter;

    /**
     * Gets the value of the hackystat property.
     * 
     * @return
     *     possible object is
     *     {@link Hackystat }
     *     
     */
    public Hackystat getHackystat() {
        return hackystat;
    }

    /**
     * Sets the value of the hackystat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hackystat }
     *     
     */
    public void setHackystat(Hackystat value) {
        this.hackystat = value;
    }

    /**
     * Gets the value of the nabaztag property.
     * 
     * @return
     *     possible object is
     *     {@link Nabaztag }
     *     
     */
    public Nabaztag getNabaztag() {
        return nabaztag;
    }

    /**
     * Sets the value of the nabaztag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nabaztag }
     *     
     */
    public void setNabaztag(Nabaztag value) {
        this.nabaztag = value;
    }

    /**
     * Gets the value of the twitter property.
     * 
     * @return
     *     possible object is
     *     {@link Twitter }
     *     
     */
    public Twitter getTwitter() {
        return twitter;
    }

    /**
     * Sets the value of the twitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Twitter }
     *     
     */
    public void setTwitter(Twitter value) {
        this.twitter = value;
    }

}
