//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.19 at 10:37:25 AM GMT-10:00 
//


package org.hackystat.tickertape.tickerlingua.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}id use="required""/>
 *       &lt;attribute ref="{}sensorbase use="required""/>
 *       &lt;attribute ref="{}dailyprojectdata use="required""/>
 *       &lt;attribute ref="{}telemetry use="required""/>
 *       &lt;attribute ref="{}projectbrowser use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "HackystatService")
public class HackystatService {

    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String sensorbase;
    @XmlAttribute(required = true)
    protected String dailyprojectdata;
    @XmlAttribute(required = true)
    protected String telemetry;
    @XmlAttribute(required = true)
    protected String projectbrowser;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sensorbase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorbase() {
        return sensorbase;
    }

    /**
     * Sets the value of the sensorbase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorbase(String value) {
        this.sensorbase = value;
    }

    /**
     * Gets the value of the dailyprojectdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDailyprojectdata() {
        return dailyprojectdata;
    }

    /**
     * Sets the value of the dailyprojectdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDailyprojectdata(String value) {
        this.dailyprojectdata = value;
    }

    /**
     * Gets the value of the telemetry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelemetry() {
        return telemetry;
    }

    /**
     * Sets the value of the telemetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelemetry(String value) {
        this.telemetry = value;
    }

    /**
     * Gets the value of the projectbrowser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectbrowser() {
        return projectbrowser;
    }

    /**
     * Sets the value of the projectbrowser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectbrowser(String value) {
        this.projectbrowser = value;
    }

}
