//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.19 at 10:37:25 AM GMT-10:00 
//


package org.hackystat.tickertape.tickerlingua.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EmailAccount"/>
 *         &lt;element ref="{}HackystatAccount"/>
 *         &lt;element ref="{}TwitterAccountRef" minOccurs="0"/>
 *         &lt;element ref="{}FacebookAccountRef" minOccurs="0"/>
 *         &lt;element ref="{}SmsAccount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}id use="required""/>
 *       &lt;attribute ref="{}fullname use="required""/>
 *       &lt;attribute ref="{}shortname use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emailAccount",
    "hackystatAccount",
    "twitterAccountRef",
    "facebookAccountRef",
    "smsAccount"
})
@XmlRootElement(name = "HackystatUser")
public class HackystatUser {

    @XmlElement(name = "EmailAccount", required = true)
    protected EmailAccount emailAccount;
    @XmlElement(name = "HackystatAccount", required = true)
    protected HackystatAccount hackystatAccount;
    @XmlElement(name = "TwitterAccountRef")
    protected TwitterAccountRef twitterAccountRef;
    @XmlElement(name = "FacebookAccountRef")
    protected FacebookAccountRef facebookAccountRef;
    @XmlElement(name = "SmsAccount")
    protected SmsAccount smsAccount;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected String fullname;
    @XmlAttribute(required = true)
    protected String shortname;

    /**
     * Gets the value of the emailAccount property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAccount }
     *     
     */
    public EmailAccount getEmailAccount() {
        return emailAccount;
    }

    /**
     * Sets the value of the emailAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAccount }
     *     
     */
    public void setEmailAccount(EmailAccount value) {
        this.emailAccount = value;
    }

    /**
     * Gets the value of the hackystatAccount property.
     * 
     * @return
     *     possible object is
     *     {@link HackystatAccount }
     *     
     */
    public HackystatAccount getHackystatAccount() {
        return hackystatAccount;
    }

    /**
     * Sets the value of the hackystatAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link HackystatAccount }
     *     
     */
    public void setHackystatAccount(HackystatAccount value) {
        this.hackystatAccount = value;
    }

    /**
     * Gets the value of the twitterAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link TwitterAccountRef }
     *     
     */
    public TwitterAccountRef getTwitterAccountRef() {
        return twitterAccountRef;
    }

    /**
     * Sets the value of the twitterAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwitterAccountRef }
     *     
     */
    public void setTwitterAccountRef(TwitterAccountRef value) {
        this.twitterAccountRef = value;
    }

    /**
     * Gets the value of the facebookAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link FacebookAccountRef }
     *     
     */
    public FacebookAccountRef getFacebookAccountRef() {
        return facebookAccountRef;
    }

    /**
     * Sets the value of the facebookAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacebookAccountRef }
     *     
     */
    public void setFacebookAccountRef(FacebookAccountRef value) {
        this.facebookAccountRef = value;
    }

    /**
     * Gets the value of the smsAccount property.
     * 
     * @return
     *     possible object is
     *     {@link SmsAccount }
     *     
     */
    public SmsAccount getSmsAccount() {
        return smsAccount;
    }

    /**
     * Sets the value of the smsAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmsAccount }
     *     
     */
    public void setSmsAccount(SmsAccount value) {
        this.smsAccount = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullname(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

}
