//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.02 at 08:59:01 AM HST 
//


package org.hackystat.tickertape.tickerlingua.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hackystat.tickertape.tickerlingua.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Description_QNAME = new QName("", "Description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hackystat.tickertape.tickerlingua.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FacebookAccountRef }
     * 
     */
    public FacebookAccountRef createFacebookAccountRef() {
        return new FacebookAccountRef();
    }

    /**
     * Create an instance of {@link HackystatProjects }
     * 
     */
    public HackystatProjects createHackystatProjects() {
        return new HackystatProjects();
    }

    /**
     * Create an instance of {@link SmsAccount }
     * 
     */
    public SmsAccount createSmsAccount() {
        return new SmsAccount();
    }

    /**
     * Create an instance of {@link FacebookAccount }
     * 
     */
    public FacebookAccount createFacebookAccount() {
        return new FacebookAccount();
    }

    /**
     * Create an instance of {@link LoggingLevel }
     * 
     */
    public LoggingLevel createLoggingLevel() {
        return new LoggingLevel();
    }

    /**
     * Create an instance of {@link Globals }
     * 
     */
    public Globals createGlobals() {
        return new Globals();
    }

    /**
     * Create an instance of {@link Ticker }
     * 
     */
    public Ticker createTicker() {
        return new Ticker();
    }

    /**
     * Create an instance of {@link EmailAccount }
     * 
     */
    public EmailAccount createEmailAccount() {
        return new EmailAccount();
    }

    /**
     * Create an instance of {@link HackystatProject }
     * 
     */
    public HackystatProject createHackystatProject() {
        return new HackystatProject();
    }

    /**
     * Create an instance of {@link Tickertapes }
     * 
     */
    public Tickertapes createTickertapes() {
        return new Tickertapes();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link TwitterAccountRef }
     * 
     */
    public TwitterAccountRef createTwitterAccountRef() {
        return new TwitterAccountRef();
    }

    /**
     * Create an instance of {@link Nabaztags }
     * 
     */
    public Nabaztags createNabaztags() {
        return new Nabaztags();
    }

    /**
     * Create an instance of {@link HackystatUserRef }
     * 
     */
    public HackystatUserRef createHackystatUserRef() {
        return new HackystatUserRef();
    }

    /**
     * Create an instance of {@link HackystatService }
     * 
     */
    public HackystatService createHackystatService() {
        return new HackystatService();
    }

    /**
     * Create an instance of {@link HackystatUser }
     * 
     */
    public HackystatUser createHackystatUser() {
        return new HackystatUser();
    }

    /**
     * Create an instance of {@link TwitterAccount }
     * 
     */
    public TwitterAccount createTwitterAccount() {
        return new TwitterAccount();
    }

    /**
     * Create an instance of {@link HackystatAccount }
     * 
     */
    public HackystatAccount createHackystatAccount() {
        return new HackystatAccount();
    }

    /**
     * Create an instance of {@link NabaztagRef }
     * 
     */
    public NabaztagRef createNabaztagRef() {
        return new NabaztagRef();
    }

    /**
     * Create an instance of {@link HackystatServices }
     * 
     */
    public HackystatServices createHackystatServices() {
        return new HackystatServices();
    }

    /**
     * Create an instance of {@link Nabaztag }
     * 
     */
    public Nabaztag createNabaztag() {
        return new Nabaztag();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link TwitterAccounts }
     * 
     */
    public TwitterAccounts createTwitterAccounts() {
        return new TwitterAccounts();
    }

    /**
     * Create an instance of {@link HackystatProjectRef }
     * 
     */
    public HackystatProjectRef createHackystatProjectRef() {
        return new HackystatProjectRef();
    }

    /**
     * Create an instance of {@link TickerLingua }
     * 
     */
    public TickerLingua createTickerLingua() {
        return new TickerLingua();
    }

    /**
     * Create an instance of {@link Mail }
     * 
     */
    public Mail createMail() {
        return new Mail();
    }

    /**
     * Create an instance of {@link HackystatUsers }
     * 
     */
    public HackystatUsers createHackystatUsers() {
        return new HackystatUsers();
    }

    /**
     * Create an instance of {@link FacebookAccounts }
     * 
     */
    public FacebookAccounts createFacebookAccounts() {
        return new FacebookAccounts();
    }

    /**
     * Create an instance of {@link Tickertape }
     * 
     */
    public Tickertape createTickertape() {
        return new Tickertape();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
