//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.19 at 10:37:25 AM GMT-10:00 
//


package org.hackystat.tickertape.tickerlingua.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Globals" minOccurs="0"/>
 *         &lt;element ref="{}HackystatServices"/>
 *         &lt;element ref="{}HackystatUsers"/>
 *         &lt;element ref="{}HackystatProjects"/>
 *         &lt;element ref="{}Nabaztags" minOccurs="0"/>
 *         &lt;element ref="{}TwitterAccounts" minOccurs="0"/>
 *         &lt;element ref="{}FacebookAccounts" minOccurs="0"/>
 *         &lt;element ref="{}Tickertapes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globals",
    "hackystatServices",
    "hackystatUsers",
    "hackystatProjects",
    "nabaztags",
    "twitterAccounts",
    "facebookAccounts",
    "tickertapes"
})
@XmlRootElement(name = "TickerLingua")
public class TickerLingua {

    @XmlElement(name = "Globals")
    protected Globals globals;
    @XmlElement(name = "HackystatServices", required = true)
    protected HackystatServices hackystatServices;
    @XmlElement(name = "HackystatUsers", required = true)
    protected HackystatUsers hackystatUsers;
    @XmlElement(name = "HackystatProjects", required = true)
    protected HackystatProjects hackystatProjects;
    @XmlElement(name = "Nabaztags")
    protected Nabaztags nabaztags;
    @XmlElement(name = "TwitterAccounts")
    protected TwitterAccounts twitterAccounts;
    @XmlElement(name = "FacebookAccounts")
    protected FacebookAccounts facebookAccounts;
    @XmlElement(name = "Tickertapes", required = true)
    protected Tickertapes tickertapes;

    /**
     * Gets the value of the globals property.
     * 
     * @return
     *     possible object is
     *     {@link Globals }
     *     
     */
    public Globals getGlobals() {
        return globals;
    }

    /**
     * Sets the value of the globals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globals }
     *     
     */
    public void setGlobals(Globals value) {
        this.globals = value;
    }

    /**
     * Gets the value of the hackystatServices property.
     * 
     * @return
     *     possible object is
     *     {@link HackystatServices }
     *     
     */
    public HackystatServices getHackystatServices() {
        return hackystatServices;
    }

    /**
     * Sets the value of the hackystatServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link HackystatServices }
     *     
     */
    public void setHackystatServices(HackystatServices value) {
        this.hackystatServices = value;
    }

    /**
     * Gets the value of the hackystatUsers property.
     * 
     * @return
     *     possible object is
     *     {@link HackystatUsers }
     *     
     */
    public HackystatUsers getHackystatUsers() {
        return hackystatUsers;
    }

    /**
     * Sets the value of the hackystatUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link HackystatUsers }
     *     
     */
    public void setHackystatUsers(HackystatUsers value) {
        this.hackystatUsers = value;
    }

    /**
     * Gets the value of the hackystatProjects property.
     * 
     * @return
     *     possible object is
     *     {@link HackystatProjects }
     *     
     */
    public HackystatProjects getHackystatProjects() {
        return hackystatProjects;
    }

    /**
     * Sets the value of the hackystatProjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link HackystatProjects }
     *     
     */
    public void setHackystatProjects(HackystatProjects value) {
        this.hackystatProjects = value;
    }

    /**
     * Gets the value of the nabaztags property.
     * 
     * @return
     *     possible object is
     *     {@link Nabaztags }
     *     
     */
    public Nabaztags getNabaztags() {
        return nabaztags;
    }

    /**
     * Sets the value of the nabaztags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nabaztags }
     *     
     */
    public void setNabaztags(Nabaztags value) {
        this.nabaztags = value;
    }

    /**
     * Gets the value of the twitterAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link TwitterAccounts }
     *     
     */
    public TwitterAccounts getTwitterAccounts() {
        return twitterAccounts;
    }

    /**
     * Sets the value of the twitterAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwitterAccounts }
     *     
     */
    public void setTwitterAccounts(TwitterAccounts value) {
        this.twitterAccounts = value;
    }

    /**
     * Gets the value of the facebookAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link FacebookAccounts }
     *     
     */
    public FacebookAccounts getFacebookAccounts() {
        return facebookAccounts;
    }

    /**
     * Sets the value of the facebookAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacebookAccounts }
     *     
     */
    public void setFacebookAccounts(FacebookAccounts value) {
        this.facebookAccounts = value;
    }

    /**
     * Gets the value of the tickertapes property.
     * 
     * @return
     *     possible object is
     *     {@link Tickertapes }
     *     
     */
    public Tickertapes getTickertapes() {
        return tickertapes;
    }

    /**
     * Sets the value of the tickertapes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tickertapes }
     *     
     */
    public void setTickertapes(Tickertapes value) {
        this.tickertapes = value;
    }

}
